// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV0_T9LTvbKq91vORvETbs0_QVf8PDd2E',
    appId: '1:751256331187:web:83abeb20057953cb6821c6',
    messagingSenderId: '751256331187',
    projectId: 'lithe-saga-473914-b3',
    authDomain: 'lithe-saga-473914-b3.firebaseapp.com',
    storageBucket: 'lithe-saga-473914-b3.firebasestorage.app',
    measurementId: 'G-P6275NG06F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyi6RD22k20waqUi6CnJFYJ7ZuyHw0uZw',
    appId: '1:751256331187:android:f2edbf86fb54cd1b6821c6',
    messagingSenderId: '751256331187',
    projectId: 'lithe-saga-473914-b3',
    storageBucket: 'lithe-saga-473914-b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnHtYMNd-utEQ2d2bHKqOyfJs6wC0nNc',
    appId: '1:751256331187:ios:ffb1797ba242ee026821c6',
    messagingSenderId: '751256331187',
    projectId: 'lithe-saga-473914-b3',
    storageBucket: 'lithe-saga-473914-b3.firebasestorage.app',
    androidClientId: '751256331187-j1930kqdmq2cgam89dp8mvo50kmejfj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSombriYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnHtYMNd-utEQ2d2bHKqOyfJs6wC0nNc',
    appId: '1:751256331187:ios:ffb1797ba242ee026821c6',
    messagingSenderId: '751256331187',
    projectId: 'lithe-saga-473914-b3',
    storageBucket: 'lithe-saga-473914-b3.firebasestorage.app',
    androidClientId: '751256331187-j1930kqdmq2cgam89dp8mvo50kmejfj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSombriYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV0_T9LTvbKq91vORvETbs0_QVf8PDd2E',
    appId: '1:751256331187:web:3bcf141bcdfac2896821c6',
    messagingSenderId: '751256331187',
    projectId: 'lithe-saga-473914-b3',
    authDomain: 'lithe-saga-473914-b3.firebaseapp.com',
    storageBucket: 'lithe-saga-473914-b3.firebasestorage.app',
    measurementId: 'G-K7ECXD65TG',
  );
}
